setwd('C:/Users/GUSTAVO/Desktop/Data analisys/exdata_data_NEI_data')
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
Maryland<-subset(NEI, fips=="24510" )
with (Maryland, plot(year,Emissions,  pch=20, ylab = "Total Emissions in Maryland Ton/year")) 